version: "3"

services:
    web:
        build: .
        volumes:
        - .:/code
        ports:
        - "80:80"
        environment:    
            MONGODB_DATABASE: med
            MONGODB_USERNAME: user-admin
            MONGODB_PASSWORD: $MONGODB_PASSWORD
            MONGODB_HOSTNAME: mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:3.4.2
        container_name: mongodb
        restart: unless-stopped
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
            MONGO_INITDB_DATABASE: med
            MONGODB_DATA_DIR: /data/db
            MONDODB_LOG_DIR: /dev/null
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

# volumes:
#     mongodbdata:
#         driver: local